### PR TITLE
0.14 serial

### PR DESCRIPTION
**Pull request by OlivierDelbeke**
Using a thread to read the serial port.
Dramatically reduces the CPU usage when the GPS NMEA plugin is used.

### CODE REVIEW

**Comment by OlivierDelbeke** [comment]
Thanks ; I will have a look at AsyncQueue (but I may not have much time in the next few days).
Something against this PR is that each call to read() will only return one message. Instead, it should all the messages read since the last call. But that's easy to fix and I will try to do it soon.

**Comment by OlivierDelbeke** [comment]
Another remark : as we are using glib, it should be possible not to use a dedicated thread to read the serial line. The glib main loop should poll()/select() on the file descriptor of the serial device and only call read() when there has been activity on it. I think that this matches your original implementation. However, something did not seem to work correctly (at least with my USB/serial device) : the CPU read() function was called continuously (=> nearly 100% CPU usage just for the GPS). A bugfix for just that, instead of the addition of a thread might do the trick.

**Comment by tripzero** [comment]
Good plan

**Comment by OlivierDelbeke** [comment]
Closing this pull request. I will fix the issue using the glib API and create another one.

**Pull request closed without merging**
