### PR TITLE
cmake: explicitly set std to c++14

### PR DESCRIPTION
**Pull request by tripzero**
Minor change now that c++14 is now a complete standard.

### CODE REVIEW

**Comment by OlivierDelbeke** [comment]
Could I remind you that the automotive-message-broker is made for the embedded world, where we often get the toolchain from the chip manufacturers, and that those toolchains are usually very old ? I fear that c++14 will in many cases NOT be supported. IMHO, it is a bad idea to force the usage of too recent compilers. In this particular case, it would be better to just replace some of the "auto".

**Comment by petr-nechaev** [comment]
I totally agree with Olivier.  For example, the toolchain we're using is stuck at gcc 4.8.2

**Comment by OlivierDelbeke** [comment]
Thanks petr-nechaev (I also think that we have gcc 4.8.2 for our main project). 
BTW, I just did a test on my PC, which runs a recent Mint distribution (17.1 - less than a year old), which comes with gcc 4.8.4 : even with this setup, the master branch does not compile : 
lib/listplusplus.h:30:85: error: parameter declared ‘auto’
  return std::any_of(iteratable.begin(), iteratable.end(), [value, &comparator](auto i) { return comparator(value, i); });
Thanks for re-evaluating this.

**Comment by tripzero** [comment]
I have a Pull Request on the 0.14 branch that removes c++14 support
reverting back to c++11.  Generic lambda support is in gcc 4.9[1].  We'll
get there.  In the meantime, we should probably revert master to c++11 also.

[1] - https://gcc.gnu.org/projects/cxx1y.html,
https://isocpp.org/files/papers/N3649.html

**Pull request merged**
