### PR TITLE
Fixes and improvements in CAN support

### PR DESCRIPTION
**Pull request by petr-nechaev**
Changes to *.dbc file grammar were tested on few very large *.dbc files. Now, it should be able to handle manually written files as well as ones, saved in Vector Candb++.

### CODE REVIEW

**Comment by tripzero** [comment]
Other than a few tabbing issues, it looks good to me.

**Comment by petr-nechaev** [comment]
Fixed tabbing, sorry.
Although spaces/tabs are mixed across the project, I don't think making them consistent in "one big commit" is a good idea, because it would complicate change tracking.

**Comment by tripzero** [comment]
Agreed.  I'm mostly concerned with keeping tabs were they are currently
used.

**Comment by tripzero** [comment]
Per development policy, I'll keep this open for a few more days for any further review and then merge it in.

**Comment by petr-nechaev** [comment]
I'm currently implementing CAN_BCM (SocketCAN) protocol support.  AFAIK this is the best way to handle cyclic (periodic) CAN messages because all timeouts, periods etc are handled by kernel code.

**Comment by tripzero** [comment]
>> I'm currently implementing CAN_BCM (SocketCAN) protocol support. AFAIK this is the best way to handle cyclic (periodic) CAN messages because all timeouts, periods etc are handled by kernel code.

As well as filters too :-).

**Comment by tripzero** [comment]
Please rebase.  Thanks.

**Comment by petr-nechaev** [comment]
CAN_BCM support added, alpha version.  Checked at 1 Mbps, the performance is quite better

Also, removed  redundant code in core. May be a bad hack because elements have to be removed from queues on application exit.

Some tab/space issues remain.

**Comment by tripzero** [comment]
Do you have a patch pending to fix the latest tabbing issues?

**Comment by petr-nechaev** [comment]
Yes, I'm double-checking it

**Comment by petr-nechaev** [comment]
Made tabbing consistent in thread.cpp

**Comment by xentnex** [comment]
2015-04-03 19:57 GMT+03:00 Petr Nechaev <notifications@github.com>:

**Comment by tripzero** [comment]
Merged

**Pull request merged**
